routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('/categories', App\Http\Controllers\CategoryManagement\CategoryController::class);
    Route::resource('/books', App\Http\Controllers\BookManagement\BookController::class);
});

app/Http/Controllers/Api/CategoryManagement/CategoryController.php
<?php

namespace App\Http\Controllers\Api\CategoryManagement;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /* Getting the request parameters. */
        $detail = $request->detail;
        $search = $request->search;

        /* A query builder. */
        $categories = (new Category)->newQuery();
        if ($request->search) {
            $categories->where('name', 'LIKE', "%{$search}%");
        }
        if ($detail == "true") {
            $categories->with('books');
        }
        $categories = $categories->get();

        /* This is a conditional statement that checks if the categories are not found. If the
        categories are not found, it returns a response with a 404 status code. */
        if(!count($categories)){
            return response()->json([
                'success'   => false,
                'message'   => 'Categories not found',
                'data'      => [],
            ], 404);
        }

        /* Returning a JSON response. */
        return response()->json([
            'success'   => true,
            'message'   => 'Categories fetched successfully',
            'data'      => $categories,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /* Finding the category with the given id. */
        $category = Category::with('books')->find($id);

        /* This is a conditional statement that checks if the category is not found. If the category is
        not found, it returns a response with a 404 status code. */
        if (empty($category)) {
            return response()->json([
                'success'   => false,
                'message'   => 'Category not found',
                'data'      => (object)[],
            ], 404);
        }

        /* Returning a JSON response. */
        return response()->json([
            'success'   => true,
            'message'   => 'Category fetched successfully',
            'data'      => $category,
        ]);
    }
}

app/Http/Controllers/CategoryManagement/CategoryController.php
<?php

namespace App\Http\Controllers\CategoryManagement;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all()->sortBy('name');
        return view('categorymanagement.index')->with(compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categorymanagement.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // rules validator
        $validate = $request->validate([
            'name'          => ['required', 'string', 'max:255'],
            'description'   => ['nullable', 'string', 'max:255'],
        ]);

        try {
            // create new category
            $category = Category::create([
                'name'          => $request->name,
                'description'   => $request->description,
            ]);
        } catch (\Throwable $th) {
            report($th);
            return redirect()->route('categories.index')
            ->with('error', 'Something wrong, Category fail to create');
        }

        return redirect()->route('categories.index')
            ->with('success', 'Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categorymanagement.show')->with(compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categorymanagement.edit')->with(compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        // rules validator
        $validate = $request->validate([
            'name'          => ['required', 'string', 'max:255'],
            'description'   => ['nullable', 'string', 'max:255'],
        ]);

        try {
            $category->update($request->all());
        } catch (\Throwable $th) {
            report($th);
            return redirect()->route('categories.index')
            ->with('error', 'Something wrong, Category fail to update');
        }

        return redirect()->route('categories.index')
            ->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        try {
            $category->delete();
        } catch (\Throwable $th) {
            report($th);
            return redirect()->route('categories.index')
            ->with('error', 'Something wrong, Category fail to delete');
        }

        return redirect()->route('categories.index')
            ->with('success', 'Category deleted successfully.');
    }
}

resources/views/categorymanagement/create.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-8 col-lg-12 col-sm-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <h3>Create New Category</h3>
                    </div>
                    <div class="card-body">
                        <p class="card-description">
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </p>
                        <form class="forms-sample" action="{{ route('categories.store') }}" method="post"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Name</label>
                                <div class="col-sm-9">
                                    <input name="name" type="text" class="form-control" id=""
                                        placeholder="Thriller">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control" id="" cols="30" rows="4"
                                        placeholder="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum libero veritatis sint aspernatur quia iste, ratione nihil explicabo maiores deserunt enim error eius dolorum sunt dolor dicta beatae aliquid saepe!"></textarea>
                                </div>
                            </div>
                            <div class="row float-right">
                                <a href="{{ route('categories.index') }}" class="btn btn-secondary mr-2">Cancel</a>
                                <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/categorymanagement/edit.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-8 col-lg-12 col-sm-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <h3>Category Edit</h3>
                    </div>
                    <div class="card-body">
                        <p class="card-description">
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </p>
                        <form class="forms-sample" action="{{ route('categories.update', $category->id) }}" method="post"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Device Name</label>
                                <div class="col-sm-9">
                                    <input name="name" type="text" class="form-control" id=""
                                        placeholder="Name" value="{{ $category->name }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control" id="" cols="30" rows="4"
                                        placeholder="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum libero veritatis sint aspernatur quia iste, ratione nihil explicabo maiores deserunt enim error eius dolorum sunt dolor dicta beatae aliquid saepe!">{{ $category->description }}</textarea>
                                </div>
                            </div>
                            <div class="row float-right">
                                <a href="{{ route('categories.index') }}" class="btn btn-secondary mr-2">Cancel</a>
                                <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/categorymanagement/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        @if ($message = Session::get('success'))
            <div class="alert alert-dismissable alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span>{{ $message }}</span>
            </div>
        @elseif ($message = Session::get('error'))
            <div class="alert alert-dismissable alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span>{{ $message }}</span>
            </div>
        @endif

        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-header">
                        <h3>Category List</h3>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-sm btn-gradient-primary" href="{{ route('categories.create') }}"><i
                                class="mdi mdi-plus"></i> Create</a>
                        <div class="table-responsive mt-4">
                            <table id="example" class="table table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($categories as $category)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $category->name }}</td>
                                            <td>{{ $category->description }}</td>
                                            <td>
                                                <form action="{{ route('categories.destroy', $category->id) }}"
                                                    method="POST">
                                                    <div class="btn-group">
                                                        <a class="btn btn-sm btn-info view_modal color"
                                                            href="{{ route('categories.show', $category->id) }}"><i
                                                                class="mdi mdi-eye"></i></a>
                                                        <a class="btn btn-sm btn-warning edit_modal color"
                                                            href="{{ route('categories.edit', $category->id) }}"><i
                                                                class="mdi mdi-grease-pencil"></i></a>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-sm btn-danger delete color"
                                                            onclick="return confirm('You will delete all data that relate to this?');"><i
                                                                class="mdi mdi-delete"></i></button>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="4">
                                                <center>Empty Data</center>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        })
    </script>
@stop

resources/views/categorymanagement/show.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-8 col-lg-12 col-sm-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <h3>Category Detail</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Name</label>
                            <div class="col-sm-9">
                                <input name="name" type="text" class="form-control" id="" placeholder="Name"
                                    value="{{ $category->name }}" readonly="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <textarea name="description" class="form-control" id="" cols="30" rows="4" readonly>{{ $category->description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Books</label>
                            <div class="col-sm-9">
                                <div class="table-responsive">
                                    <table id="example" class="table table-bordered" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Title</th>
                                                <th>Author</th>
                                                <th>Year</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse ($category->books as $book)
                                                <tr>
                                                    <td>{{ $loop->index + 1 }}</td>
                                                    <td> {{ $book->title }} </td>
                                                    <td> {{ $book->author }} </td>
                                                    <td> {{ $book->year }} </td>
                                                </tr>
                                            @empty
                                                <tr>
                                                    <td colspan="4">
                                                        <center>Empty Data</center>
                                                    </td>
                                                </tr>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="row float-right">
                            <a href="{{ route('categories.index') }}" class="btn btn-secondary mr-2">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        })
    </script>
@stop