routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('/categories', App\Http\Controllers\CategoryManagement\CategoryController::class);
    Route::resource('/books', App\Http\Controllers\BookManagement\BookController::class);
});

app/Http/Controllers/Api/BookManagement/BookController.php
<?php

namespace App\Http\Controllers\Api\BookManagement;

use App\Http\Controllers\Controller;
use App\Models\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /* Getting the request parameters. */
        $detail = $request->detail;
        $search = $request->search;

        /* A query builder. */
        $books = (new Book)->newQuery();
        if ($request->search) {
            $books->where('title', 'LIKE', "%{$search}%")
                ->orWhere('author', 'LIKE', "%{$search}%")
                ->orWhere('year', 'LIKE', "%{$search}%");
        }
        if ($detail == "true") {
            $books->with('category');
        }
        $books = $books->get();

        /* This is a conditional statement that checks if the books are not found. If the
        books are not found, it returns a response with a 404 status code. */
        if(!count($books)){
            return response()->json([
                'success'   => false,
                'message'   => 'Books not found',
                'data'      => [],
            ], 404);
        }

        /* Returning a JSON response. */
        return response()->json([
            'success'   => true,
            'message'   => 'Books fetched successfully',
            'data'      => $books,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /* Finding the book with the given id. */
        $book = Book::with('category')->find($id);

        /* This is a conditional statement that checks if the book is not found. If the book is
        not found, it returns a response with a 404 status code. */
        if (empty($book)) {
            return response()->json([
                'success'   => false,
                'message'   => 'Book not found',
                'data'      => (object)[],
            ], 404);
        }

        /* Returning a JSON response. */
        return response()->json([
            'success'   => true,
            'message'   => 'Book fetched successfully',
            'data'      => $book,
        ]);
    }
}

app/Http/Controllers/BookManagement/BookController.php
<?php

namespace App\Http\Controllers\BookManagement;

use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all()->sortByDesc('year');
        return view('bookmanagement.index')->with(compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all()->sortBy('name');
        return view('bookmanagement.create')->with(compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // rules validator
        $validate = $request->validate([
            'title'         => ['required', 'string', 'max:255'],
            'description'   => ['nullable', 'string', 'max:255'],
            'author'        => ['required', 'string', 'max:255'],
            'year'          => ['required', 'numeric'],
            'category_id'   => ['required', 'numeric'],
        ]);

        try {
            // create new book
            $book = Book::create([
                'category_id'   => $request->category_id,
                'title'         => $request->title,
                'description'   => $request->description,
                'author'        => $request->author,
                'year'          => $request->year,
            ]);
        } catch (\Throwable $th) {
            report($th);
            return redirect()->route('books.index')
            ->with('error', 'Something wrong, Book fail to create');
        }

        return redirect()->route('books.index')
            ->with('success', 'Book created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        return view('bookmanagement.show')->with(compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $categories = Category::all()->sortBy('name');
        return view('bookmanagement.edit')->with(compact('book', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        // rules validator
        $validate = $request->validate([
            'category_id'   => ['required', 'numeric'],
            'title'         => ['required', 'string', 'max:255'],
            'description'   => ['nullable', 'string', 'max:255'],
            'author'        => ['required', 'string', 'max:255'],
            'year'          => ['required', 'numeric'],
        ]);

        try {
            $book->update($request->all());
        } catch (\Throwable $th) {
            report($th);
            return redirect()->route('books.index')
            ->with('error', 'Something wrong, Book fail to update');
        }

        return redirect()->route('books.index')
            ->with('success', 'Book updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        try {
            $book->delete();
        } catch (\Throwable $th) {
            report($th);
            return redirect()->route('books.index')
            ->with('error', 'Something wrong, Book fail to delete');
        }

        return redirect()->route('books.index')
            ->with('success', 'Book deleted successfully.');
    }
}

resources/views/bookmanagement/create.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-8 col-lg-12 col-sm-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <h3>Create New Book</h3>
                    </div>
                    <div class="card-body">
                        <p class="card-description">
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </p>
                        <form class="forms-sample" action="{{ route('books.store') }}" method="post"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Title</label>
                                <div class="col-sm-9">
                                    <input name="title" type="text" class="form-control" id=""
                                        placeholder="Lorem ipsum dolor sit amet" value="{{ old('title') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control" id="" cols="30" rows="4"
                                        placeholder="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum libero veritatis sint aspernatur quia iste, ratione nihil explicabo maiores deserunt enim error eius dolorum sunt dolor dicta beatae aliquid saepe!">{{ old('description') }}</textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Author</label>
                                <div class="col-sm-9">
                                    <input name="author" type="text" class="form-control" id=""
                                        placeholder="John Doe" value="{{ old('author') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Year</label>
                                <div class="col-sm-9">
                                    <input name="year" type="number" class="form-control" id=""
                                        placeholder="2000" value="{{ old('year') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Category</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="category_id">
                                        @foreach ($categories as $category)
                                            {{-- <option value="{{ $category->id }}">{{ $category->name }}
                                            </option> --}}
                                            <option value="{{ $category->id }}"
                                                {{ $category->id == old('category_id') ? 'selected' : '' }}>
                                                {{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row float-right">
                                <a href="{{ route('books.index') }}" class="btn btn-secondary mr-2">Cancel</a>
                                <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/bookmanagement/edit.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-8 col-lg-12 col-sm-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <h3>Book Edit</h3>
                    </div>
                    <div class="card-body">
                        <p class="card-description">
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </p>
                        <form class="forms-sample" action="{{ route('books.update', $book->id) }}" method="post"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Title</label>
                                <div class="col-sm-9">
                                    <input name="title" type="text" class="form-control" id=""
                                        placeholder="Lorem ipsum dolor sit amet" value="{{ $book->title }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control" id="" cols="30" rows="4"
                                        placeholder="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum libero veritatis sint aspernatur quia iste, ratione nihil explicabo maiores deserunt enim error eius dolorum sunt dolor dicta beatae aliquid saepe!">{{ $book->description }}</textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Author</label>
                                <div class="col-sm-9">
                                    <input name="author" type="text" class="form-control" id=""
                                        placeholder="John Doe" value="{{ $book->author }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Year</label>
                                <div class="col-sm-9">
                                    <input name="year" type="number" class="form-control" id=""
                                        placeholder="2000" value="{{ $book->year }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-sm-3 col-form-label">Category</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="category_id">
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}"
                                                {{ $category->id == $book->category_id ? 'selected' : '' }}>
                                                {{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row float-right">
                                <a href="{{ route('books.index') }}" class="btn btn-secondary mr-2">Cancel</a>
                                <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/bookmanagement/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        @if ($message = Session::get('success'))
            <div class="alert alert-dismissable alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span>{{ $message }}</span>
            </div>
        @elseif ($message = Session::get('error'))
            <div class="alert alert-dismissable alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span>{{ $message }}</span>
            </div>
        @endif

        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-header">
                        <h3>Book List</h3>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-sm btn-gradient-primary" href="{{ route('books.create') }}"><i
                                class="mdi mdi-plus"></i> Create</a>
                        <div class="table-responsive mt-4">
                            <table id="example" class="table table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th>Year</th>
                                        <th>Category</th>
                                        <th>Description</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($books as $book)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $book->title }}</td>
                                            <td>{{ $book->author }}</td>
                                            <td>{{ $book->year }}</td>
                                            @if ($book->category)
                                                <td>{{ $book->category->name }}</td>
                                            @else
                                                <td>-</td>
                                            @endif
                                            <td>{{ $book->description }}</td>
                                            <td>
                                                <form action="{{ route('books.destroy', $book->id) }}" method="POST">
                                                    <div class="btn-group">
                                                        <a class="btn btn-sm btn-info view_modal color"
                                                            href="{{ route('books.show', $book->id) }}"><i
                                                                class="mdi mdi-eye"></i></a>
                                                        <a class="btn btn-sm btn-warning edit_modal color"
                                                            href="{{ route('books.edit', $book->id) }}"><i
                                                                class="mdi mdi-grease-pencil"></i></a>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-sm btn-danger delete color"
                                                            onclick="return confirm('You will delete all data that relate to this?');"><i
                                                                class="mdi mdi-delete"></i></button>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7">
                                                <center>Empty Data</center>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        })
    </script>
@stop

resources/views/bookmanagement/show.blade.php
@extends('layouts.layout')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-8 col-lg-12 col-sm-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <h3>Book Detail</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Title</label>
                            <div class="col-sm-9">
                                <input name="title" type="text" class="form-control" id="" placeholder="Name"
                                    value="{{ $book->title }}" readonly="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <textarea name="description" class="form-control" id="" cols="30" rows="4" readonly>{{ $book->description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Author</label>
                            <div class="col-sm-9">
                                <input name="author" type="text" class="form-control" id=""
                                    placeholder="John Doe" value="{{ $book->author }}" readonly>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Year</label>
                            <div class="col-sm-9">
                                <input name="year" type="number" class="form-control" id="" placeholder="2000"
                                    value="{{ $book->year }}" readonly>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Category</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="category_id">
                                    <option value="{{ $book->category->id }}" disabled selected>{{ $book->category->name }}
                                    </option>
                                </select>
                            </div>
                        </div>
                        <div class="row float-right">
                            <a href="{{ route('books.index') }}" class="btn btn-secondary mr-2">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop